swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
schemes:
  - http
paths:
  /user/login:
    post:
      parameters:
        - name: login
          in: query
          description: "имя пользователя для входа"
          required: true
          type: string
        - name: password
          in: query
          description: "Пароль"
          required: true
          type: string
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid username/password supplied"